CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	email_verified BOOLEAN DEFAULT false,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(60) NOT NULL,
	profile_url VARCHAR(255)
);
