version: "3.8"

services:

  express:
    build: .
    ports:
      - "7890:7890"
    depends_on:
      - "mysql"
    environment:
      NODE_ENV: "${NODE_ENV}"
      SESSION_SECRET: "lalala-session-secret"
      COOKIE_DOMAIN: "localhost"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "you.dev"
      MYSQL_USER: "you-dev-rw"
      MYSQL_PASSWORD: "local-rw-password"
      MYSQL_ROOT_PASSWORD: "local_root_password"
    env_file: ".env"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "you.dev"
      MYSQL_USER: "you-dev-rw"
      MYSQL_PASSWORD: "local-rw-password"
      MYSQL_ROOT_PASSWORD: "local_root_password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
