version: "3.8"

services:

  express:
    build: .
    ports:
      - "7890:7890"
    depends_on:
      - "mysql"
    env_file: ".env"

  mysql:
    image: mysql:5.7
    command: --log-error-verbosity=2 --explicit_defaults_for_timestamp
    restart: always
    environment:
      MYSQL_DATABASE: "you.dev"
      MYSQL_USER: "you-dev-rw"
      MYSQL_PASSWORD: "local-rw-password"
      MYSQL_ROOT_PASSWORD: "local_root_password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
